# Generated by Django 3.1.2 on 2020-12-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notes',
        ),
    ]
