# Generated by Django 3.1.2 on 2020-12-14 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_auto_20201212_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
