# Generated by Django 3.1.2 on 2020-12-15 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_note_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
